# Generated by Django 4.1.5 on 2023-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "Hr"),
                    ("employee", "Employee"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=8,
            ),
        ),
    ]
