# Generated by Django 4.1.5 on 2023-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_skill_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
