# Generated by Django 4.1.5 on 2023-01-30 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_vacancy_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="min_experience",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
