# Generated by Django 4.1.5 on 2023-01-30 06:11

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0004_vacancy_min_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateField(
                null=True, validators=[vacancies.models.check_date_not_past]
            ),
        ),
    ]
